dist: xenial
services: docker
language: bash
addons:
  apt:
    sources:
        - sourceline: 'deb http://archive.ubuntu.com/ubuntu bionic main universe'
    packages:
      - debootstrap
      - qemu-user-static
env:
    global:
        - QEMU_VER=v3.1.0-3
        - DOCKER_REPO=multiarch/ubuntu-debootstrap
    matrix:
        - ARCH=amd64 INCLUDE=wget QEMU_ARCH=x86_64 SUITE=trusty UNAME_ARCH=x86_64 VERSION=14.04
        - ARCH=arm64 INCLUDE=wget QEMU_ARCH=aarch64 SUITE=trusty UNAME_ARCH=arm64 VERSION=14.04
        - ARCH=mips64el INCLUDE=wget QEMU_ARCH=mips64el SUITE=trusty UNAME_ARCH=mips64el VERSION=14.04
        - ARCH=ppc64el INCLUDE=wget QEMU_ARCH=ppc64 SUITE=trusty UNAME_ARCH=ppc64el VERSION=14.04

        - ARCH=amd64 INCLUDE=iproute2,wget QEMU_ARCH=x86_64 SUITE=xenial UNAME_ARCH=x86_64 VERSION=16.04
        - ARCH=arm64 INCLUDE=iproute2,wget QEMU_ARCH=aarch64 SUITE=xenial UNAME_ARCH=arm64 VERSION=16.04
        - ARCH=mips64el INCLUDE=iproute2,wget QEMU_ARCH=mips64el SUITE=xenial UNAME_ARCH=mips64el VERSION=16.04
        - ARCH=ppc64el INCLUDE=iproute2,wget QEMU_ARCH=ppc64 SUITE=xenial UNAME_ARCH=ppc64el VERSION=16.04

        - ARCH=amd64 INCLUDE=iproute2,wget QEMU_ARCH=x86_64 SUITE=bionic UNAME_ARCH=x86_64 VERSION=18.04
        - ARCH=arm64 INCLUDE=iproute2,wget QEMU_ARCH=aarch64 SUITE=bionic UNAME_ARCH=arm64 VERSION=18.04
        - ARCH=mips64el INCLUDE=iproute2,wget QEMU_ARCH=mips64el SUITE=bionic UNAME_ARCH=mips64el VERSION=18.04
script:
    - ./update.sh -a "$ARCH" -v "$VERSION" -q "$QEMU_ARCH" -u "$QEMU_VER" -d "$DOCKER_REPO" -s "$SUITE" -i "$INCLUDE" -o "$UNAME_ARCH"
after_success:
    - |
      if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && \
              docker push $DOCKER_REPO
      fi
